### PR TITLE
feature/card-input-image

### PR DESCRIPTION
**Pull request by surajmore98**
-input component added.
-image component added.
-card component added.

### CODE REVIEW

**Review by ravikumar1002 — APPROVED** [review]
everything is good but one thing is that in input.html you have used m class name, try to give more specific class name because the naming is not clear for m , try like, m-0, m-1, m-2,   if  it is possible

**Comment by ramalingaa** [comment]
Overall, Card looks good but adding padding(left and top) to text part would make it more readable and appealing.
For inputs bit space(margin) between label andd checkbox/radio would be a good choice.

**Comment by surajmore98** [comment]
@ramalingaa  made changes.

**Comment by surajmore98** [comment]
> Overall, Card looks good but adding padding(left and top) to text part would make it more readable and appealing. For inputs bit space(margin) between label andd checkbox/radio would be a good choice.

Made changes as per the suggestion.

**Review by ramalingaa — APPROVED** [review]

**Pull request merged**
